### ISSUE TITLE
Bind to specific kinds of events

### ISSUE THREAD

**Issue by pguillem** [marcelog/PAMI#100]
Hello.
Is it possible for PAMI to bind JUST to PeerStatus events?

I know for sure i can bind to (EventMessage $event) using a handler function, and then use getName() to filter for "PeerStatus events... 

... but i would not like to waste CPU listening to every single event on the AMI if the library has implemented this on a lower level.

I´m currently using:

```
public function handle(EventMessage $event)
    {
        if($event->getName() == "PeerStatus"){
                if($event->getKey("peerstatus") == "Rejected"){
                        $ip = $event->getKey("address");
                        $this->ips["$ip"] += 1;
                        echo "IP $ip has ".$this->ips["$ip"]." Failed Attempts\n";
                        if($this->ips["$ip"] > 30){
                                //Ban IP
                                if($this->ips["$ip"] != 10000){
                                        $res = shell_exec("/sbin/ipset add blacklist $ip");
                                        $this->ips["$ip"] = 10000;
                                }
                        }

                        //Flush object once in a while
                        if(size($this->ips["$ip"]) > 1024){
                                $this->ips["$ip"] = array();
                        }

                }
        }

    }
```

As you see.. i´m tired of relying on fail2ban and i implemented my own "Anti-Dictionary attack" code.. which directly BLOCKS every IP that fails to register 30 times using IPSET and IPTABLES,

Best
pedro

**Comment by marcelog** [comment]
Hello!

See this documentation: http://doxygen.asterisk.org/trunk/Config_ami.html Specifically ";eventfilter=Event: Newchannel"

Otherwise you could also use this https://wiki.asterisk.org/wiki/display/AST/Asterisk+10+ManagerAction_Filter

Cheers!

**Comment by pguillem** [comment]
Thanks
and by the way... great lib Marcelo!.

**Comment by marcelog** [comment]
Thanks man, I'm glad you like it! :)

Best!

**Comment by pguillem** [comment]
Here it is... 

just in case anyone wants to play around with PAMI / IPSET / IPTABLES for safely securing an asterisk box from being attacked by 15 year-old kids from Pakistan (LOL). make sure you have IPSET installed before exec.

[sip_security.zip](https://github.com/marcelog/PAMI/files/141423/sip_security.zip)
.

**Comment by pguillem** [comment]
Correction..

//Flush object once in a while
                        if(size($this->ips) > 1024 ){
                                $this->ips = array();
}
