### ISSUE TITLE
DialEvent in asterisk 11.10 not found?

### ISSUE THREAD

**Issue by cusco** [marcelog/PAMI#102]
Hi,

I'm just starting to try PAMI. Thank you so much for this amazing piece of code. 

basically I followed your sample code on returning 
$event instanceof DialEvent

however it does not return Dial events.

returning ALL events shows a dial as:

```
object(PAMI\Message\Event\DialEvent)#8 (6) {
  ["rawContent":protected]=>
  string(357) "Event: Dial
Privilege: call,all
SubEvent: Begin
Channel: Local/725@agents-00002e41;2
Destination: SIP/725-00005809
CallerIDNum: 256197189
CallerIDName: Cabovisao:0:256197189:1458856633.46235:SIP/fundao-pstn-00005806
ConnectedLineNum: 275759144
ConnectedLineName: <unknown>
UniqueID: 1458856646.46238
DestUniqueID: 1458856647.46240
Dialstring: 725"
  ["channelVariables":protected]=>
  array(1) {
    ["local/725@agents-00002e41;2"]=>
    array(0) {
    }
...
```

Why is it not returned as a DialEvent ? Is this different from 1.6 or 1.8 ?

**Comment by marcelog** [comment]
Sorry, but I'm not sure I'm following. The object is of type DialEvent, as the dump shows. Also, you should post the code you are using, and perhaps elaborate a bit more of what you are expecting and what is it that you're getting.

**Comment by cusco** [comment]
Hi,

Thank you for your quick reply.

If I return $event, I can see all events. 
If I return event instanceof DialEvent, no output

Why ??

OK here is a sample of the code I have:

```
<?php
// Make sure you include the composer autoload.
require __DIR__ . '/vendor/autoload.php';

use PAMI\Client\Impl\ClientImpl as PamiClient;
use PAMI\Message\Event\EventMessage;
use PAMI\Listener\IEventListener;


$options = array(
    'host'	      => 'xxx.xxx.xxx.xxx',
    'scheme'	    => 'tcp://',
    'port'	      => 5038,
    'username'	  => 'xxx',
    'secret'	    => 'xxx',
    'connect_timeout'   => 10,
    'read_timeout'      => 10
);
#$client = new \PAMI\Client\Impl\ClientImpl($options);
$client = new PamiClient($options);

class MyListener
{
    public function handlerMethod(EventMessage $event){
		echo "handler\n";
		var_dump($event);
	}
}

// Open the connection
$client->open();


// Registering a closure
$client->registerEventListener(
	function ($event){
		#echo "handler closure\n";
		var_dump($event);
	}
	,
	function(EventMessage $event){
		return
			$event
#			$event instanceof DialEvent
#			&& $event->getSubEvent() == 'Begin'
		;
	}
);

$running = true;

// Main loop
while($running) {
	$client->process();
	usleep(1000);
}

$listener = new MyListener();


// Close the connection
$client->close();
```

**Comment by marcelog** [comment]
Try using the complete namespace for DialEvent (i.e: PAMI\Message\Event\DialEvent). The Callable should return `true` or `false`. In your code you are basically saying that you want to handle all filters, since any value is different than `false`.

**Comment by cusco** [comment]
OK using the complete namespace worked. Thanks!

Do I have to use it like that?

**Comment by marcelog** [comment]
Great! To know more about why that worked and how you should write your code exactly, you should read more about php namespaces here: http://php.net/manual/en/language.namespaces.php.

Cheers!
