### ISSUE TITLE
Unknown events

### ISSUE THREAD

**Issue by xenm321** [marcelog/PAMI#120]
DialBegin (https://wiki.asterisk.org/wiki/display/AST/Asterisk+13+ManagerEvent_DialBegin):
            [event] => DialBegin
            [privilege] => call,all
            [destchannel] => SIP/200-00000146
            [destchannelstate] => 0
            [destchannelstatedesc] => Down
            [destcalleridnum] => 200
            [destcalleridname] => Centrius
            [destconnectedlinenum] => 200
            [destconnectedlinename] => <unknown>
            [destlanguage] => ru
            [destaccountcode] => 
            [destcontext] => from-internal
            [destexten] => 
            [destpriority] => 1
            [destuniqueid] => 1480491020.5726
            [destlinkedid] => 1480491020.5726
            [dialstring] => 200

DialEnd(https://wiki.asterisk.org/wiki/display/AST/Asterisk+13+ManagerEvent_DialEnd):
           [event] => DialEnd
            [privilege] => call,all
            [destchannel] => SIP/200-00000146
            [destchannelstate] => 6
            [destchannelstatedesc] => Up
            [destcalleridnum] => 200
            [destcalleridname] => Centrius
            [destconnectedlinenum] => 200
            [destconnectedlinename] => <unknown>
            [destlanguage] => ru
            [destaccountcode] => 
            [destcontext] => from-internal
            [destexten] => 
            [destpriority] => 1
            [destuniqueid] => 1480491020.5726
            [destlinkedid] => 1480491020.5726
            [dialstatus] => ANSWER

**Comment by marcelog** [comment]
Added in [b5beb39e687f0885c0f19edaf9c3d9a33a9c5c43]
