### ISSUE TITLE
Changelog for v2?

### ISSUE THREAD

**Issue by mstyles** [marcelog/PAMI#133]
I'm looking to update to v2, but I'm not sure what all has changed in it from v1. Particularly of concern, naturally, would be any backwards incompatible changes. Not sure if these versions follow semantic versioning, but a major version increase typically implies breaking changes. Could someone provide a list of at least the incompatible changes in v2? I can try do a diff through git, but I think it'd be ideal for someone who is more familiar with the changes that have been made in case I overlook something. Thank you!

**Comment by marcelog** [comment]
Hello @mstyles!

For the list of changes please see [https://github.com/marcelog/PAMI/releases/tag/v2.0.0]. The API is still pretty much the same, PEAR was deprecated and PSR-4 and PSR-3 are now used in the code. The rest is still the same.

Best!

**Comment by mstyles** [comment]
Now I feel dumb, thanks so much! :)
