### ISSUE TITLE
Real time with pami

### ISSUE THREAD

**Issue by davicfg** [marcelog/PAMI#152]
Hello guys, I'm studying a little about pami and I want to know how I can made a dashboard to show how many agens are logged, duretion of a call in progess etc.

**Comment by marcelog** [comment]
Hi,

The question is absolutely too broad to answer, sorry. Perhaps you can do more research on your side and then come back with more specific/detailed questions/issues. Start by trying PAMI and see how you can gather all the information you need from Asterisk and then design an architecture around that that may suit your needs (frontend frameworks, databases, roles, privileges, if you want to support one or many asterisk installations, and a really huge list of etcs :))

All the best with your project!

**Comment by davicfg** [comment]
I don't know if I can answer on a closed issue, but ... Here is what I crave [Dashboard](https://static1.squarespace.com/static/556c9bf4e4b0de57cb590a0f/t/5859694e03596e9f55182af7/1482254702025/?format=1000w), I want in some manths develope the same of this img.

**Comment by davicfg** [comment]
Marcelo?
