### ISSUE TITLE
Could we get a new tag on master?

### ISSUE THREAD

**Issue by mstyles** [marcelog/PAMI#190]
The last tag of master was v2.0.1 from Nov 2016. Since that time there have been a handful of additions merged to master. Could we get master tagged with a v2.0.2? or maybe v2.1.0? (either is fine by me). This would make it easier to pull in the latest additions through composer. Thanks @marcelog !

(for some reason, the "dev-master" option was recently removed from packagist, making it difficult to get the updates without an actual tag)

**Comment by marcelog** [comment]
The composer.json file was outdated, could you try again with `dev-master`? Thanks for reporting it, btw!

**Comment by mstyles** [comment]
`dev-master` is working again, as well as the new v2.0.2 release! Thanks so much for the speedy response!
