### ISSUE TITLE
AsyncClientImpl send hang

### ISSUE THREAD

**Issue by wormling** [marcelog/PAMI#39]
I noticed that when I hang up my sip client just before my Async AGI application calls something like consoleLog, the process would hang forever in send() due to         while($this->_lastAgiResult === false) {... which will always be false in this case.

See https://github.com/wormling/PAMI/commit/fa92fa4086e72deca99619de3feaba89da7456a3 for an example solution.  I think maybe pass a timeout option to the constructor and use that like you've done in ClientImpl may be cleaner though.  If you give me a suggestion, I could submit a PR for this.

**Comment by marcelog** [comment]
I think we're done with this, closing now.
