### ISSUE TITLE
DongleSendSMSAction send only first line

### ISSUE THREAD

**Issue by moutazhodhod** [marcelog/PAMI#75]
Hello,
when i try to send multi-lines SMS by DongleSendSMSAction , it's send only first line and ignore other lines .
what i can do to solve this issue ?
$SMS = new DongleSendSMSAction("dongle1", "+10987654321","hello \n Test SMS") ;
Thanks

**Comment by marcelog** [comment]
It seems you're not the only one having this issue with dongle. I suggest open them an issue.

Thanks!

**Comment by moutazhodhod** [comment]
Thank you marcelog

I can use dongle to send multi-lines sms by using "spool call file"
by put it as base64 value => base64_encode($Msg);
Setvar: SmsText=2KjYs9mFINin2YTZhNmHINin2YTYsdit2YXZhiDYp9mE2LHYrdmK2YUKCdmH2K/Zh9ivCgk=
And Use 
exten => 101,1,DongleSendSMS(dongle1,${Destination},${BASE64_DECODE(${SmsText})},1440, yes)
my issue now is only , how to send it by php PAMI ?

**Comment by marcelog** [comment]
Great!

You can manipulate call files with [PAGI](https://github.com/marcelog/PAGI), See: [http://marcelog.github.io/articles/pagi_tutorial_create_voip_telephony_application_for_asterisk_with_agi_and_php.html](http://marcelog.github.io/articles/pagi_tutorial_create_voip_telephony_application_for_asterisk_with_agi_and_php.html) the seccion called "Spooling calls through call files".

Cheers!

**Comment by moutazhodhod** [comment]
Thanks marcelog
