### ISSUE TITLE
PAMI Documentation

### ISSUE THREAD

**Issue by qasimkhans** [marcelog/PAMI#78]
Hi, 
      is there any PAMI Documentation available, which describe the events, shows how to use events and how to get some specific events values and save them in DB. Thanks.

**Comment by marcelog** [comment]
Hello,

You should be able to find anything you want in the [pami homepage](http://marcelog.github.io/PAMI/). There are links to articles, slides, and examples.

By the way, issues are meant to request new features or bug fixes. Please don't open them for these questions or to request help on specifics of your code.

Thanks!
