### ISSUE TITLE
result in variable

### ISSUE THREAD

**Issue by qasimkhans** [marcelog/PAMI#81]
Hi,
i just started using your PAMI. i can see Events and Actions results on screen. how can i save events and actions result in variable and save them in DB. is there any discussion form of PAMI?

Thanks

**Comment by marcelog** [comment]
This has nothing to do with PAMI, so I'm closing this one. You can refer to [AsterTrace](https://github.com/marcelog/AsterTrace) for a complete example that saves the events to mysql (it also does a lot of other stuff). In any case, there are a *lot* of alternatives when saving information "to a database", so it's up to you to choose the right technologies.

Best!
