### ISSUE TITLE
Use PSR-3 dependency for logger instead of log4php

### ISSUE THREAD

**Issue by johanwilfer** [marcelog/PAMI#82]
Now when there is a PSR-3 standard for logging with php, maybe the hard dependency on log4php could be replaced with a dependency on Psr\Log\LoggerInterface instead of a specific logging library.

This would allow to use any other logging library, for example Monolog etc.

Some related links:
http://www.php-fig.org/psr/psr-3/
http://www.sitepoint.com/logging-with-psr-3-to-improve-reusability/
http://www.sitepoint.com/implementing-psr-3-with-log4php/

Would a PR for this be accepted? Is anything like this already being worked on?

**Comment by marcelog** [comment]
Hello!

There's this one: https://github.com/marcelog/PAMI/pull/74 by @jacobkiers. Feel free to add your thoughts on it. I still have to a final review, testing, and merge.

**Comment by johanwilfer** [comment]
Great, it looks good. Added one minor note, but nothing aside from that.

**Comment by marcelog** [comment]
Closed with https://github.com/marcelog/PAMI/pull/83 will be ready with 1.80.0

Thanks guys!
