### ISSUE TITLE
AgentsEvent return is missing a proper end of line when agent in use

### ISSUE THREAD

**Issue by TarikAmine** [marcelog/PAMI#89]
Hello, while using PAMI i run at a problem where LoggedInTime of an agent disapear when in use, while digging i found that the event returned from the manager having the line ```CallStarted``` without a proper end of line.
```
Event: Agents\r\n
Agent: agent_doe\r\n
Name: Jhon Doe\r\n
Status: AGENT_ONCALL\r\n
TalkingToChan: SIP/1010-00000073\r\n
CallStarted: 1443613421\n
LoggedInTime: 1443608760\r\n
Channel: SIP/1234-00000060\r\n
...
```
I know it is probably a module side issue, but i wanted to put it as a heads up, while also digging for a work around since events classes are hard coded into the package

**Comment by marcelog** [comment]
Hello @TarikAmine,

Thanks for the report! Unfortunately it is quite easy to stumble upon these inconsistencies in Asterisk. There's not much to do in PAMI, perhaps you can upgrade or downgrade to an Asterisk version that respects the AMI protocol. As stated in the asterisk wiki (https://wiki.asterisk.org/wiki/display/AST/AMI+v2+Specification#AMIv2Specification-MessageSendingandReceiving)

> AMI is an ASCII protocol that provides bidirectional communication with clients. An AMI message – action or event – is composed of fields delineated by the '\r\n' characters. Within a message, each field is a key value pair delineated by a ':'. A single space MUST follow the ':' and precede the value. Fields with the same key may be repeated within an AMI message. An action or event is terminated by an additional '\r\n' character.

Just for the record, what asterisk version are you using?

**Comment by TarikAmine** [comment]
Hi @marcelog, 
Like i said i know it's an asterisk problem, and just wanted ot put it here for future lookers.
Asterisk version is 13.04

a side rant: why is everything set to private instead of protected? had to copy entire class to do a simple line change into ```AgentsEvent```?

And thank you for keeping this alive till now.

**Comment by marcelog** [comment]
Not sure what you mean, but feel free to open a pull request to suggest any needed changes/fixes :)

Will close this one now. 

Cheers!
