### ISSUE TITLE
Adding Queue or SIP or Extension with PHP using PAMI

### ISSUE THREAD

**Issue by omidkh68** [marcelog/PAMI#93]
Is it possible to add Queue, SIP, Extension, ... using PAMI with PHP? I want to know if there is a way to add these with PHP using the written class.

**Comment by marcelog** [comment]
Please keep issues to only report bugs, discuss new/current features/suggestions.

Also, you should refer to the Asterisk wiki, where you can find [the list of AMI Actions](https://wiki.asterisk.org/wiki/display/AST/AMI+Actions), and the [PAMI API documentation](http://ci.marcelog.name/job/PAMI/javadoc/) where you can find the list of available actions. You should find the actions that suit your needs and use them.

Best!
